---
- name: ensure there is no custom bind-address
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    state: absent
  notify: restart mysql
  tags:
    - templates

- name: create custom mysql config file
  template:
    src: mysql_group_replication.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysql_group_replication.cnf
  notify: restart mysql
  tags:
    - templates
  
